# Generated by Django 2.0.13 on 2019-09-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('Components', models.CharField(max_length=200)),
                ('issue_type', models.CharField(max_length=200)),
                ('comments', models.TextField(blank=True, null=True)),
                ('modified_by', models.CharField(max_length=200)),
            ],
        ),
    ]
