# Generated by Django 2.0.13 on 2019-09-17 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0003_component'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cc',
            old_name='company_name',
            new_name='company',
        ),
    ]
