# Generated by Django 2.0.13 on 2019-09-20 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0004_auto_20190917_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakeholder_name', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=60, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Components', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterIssueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cc',
            name='company',
        ),
        migrations.DeleteModel(
            name='component',
        ),
        migrations.DeleteModel(
            name='Cc',
        ),
        migrations.DeleteModel(
            name='master',
        ),
        migrations.AddField(
            model_name='issuetracker',
            name='Components',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cc.MasterComponents'),
        ),
        migrations.AddField(
            model_name='issuetracker',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cc.MasterCompany'),
        ),
        migrations.AddField(
            model_name='issuetracker',
            name='issue_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cc.MasterIssueType'),
        ),
    ]
