# Generated by Django 2.0.13 on 2019-10-14 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0005_auto_20190920_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='authentication',
            fields=[
                ('issuetracker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cc.IssueTracker')),
            ],
            bases=('cc.issuetracker',),
        ),
    ]
