# Generated by Django 2.0.13 on 2019-10-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0006_authentication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuetracker',
            old_name='Components',
            new_name='components',
        ),
        migrations.RenameField(
            model_name='mastercomponents',
            old_name='Components',
            new_name='components',
        ),
    ]
