# Generated by Django 2.0.13 on 2019-10-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0007_auto_20191015_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuetracker',
            old_name='company',
            new_name='company_name',
        ),
    ]
