# Generated by Django 2.0.13 on 2019-10-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0008_auto_20191015_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetracker',
            name='created_by',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
