# Generated by Django 2.0.13 on 2019-10-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0009_issuetracker_created_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterComponents',
            new_name='MasterCheckType',
        ),
        migrations.AddField(
            model_name='issuetracker',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
