# Generated by Django 2.0.13 on 2019-10-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0011_issuetracker_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetracker',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
